"""One short line per file: what it is for. Shown next to each file name in the guide."""

J = "backend/src/main/java/com/edumate/"
T = "backend/src/test/java/com/edumate/"
F = "frontend/src/"

FILE_TITLES = {
    ".env.example": "Example secret settings for Docker; copy to .env and change",
    ".gitattributes": "Tells git how to store line endings and binary files",
    ".gitignore": "Files git must never upload (build output, uploads, secrets)",
    "README.md": "The project's front page on GitHub: what it is and how to run it",
    "docker-compose.yml": "Starts database, cache, backend and frontend together with one command",
    "scripts/dev-start.ps1": "Windows helper: opens the backend and frontend in two windows",
    "backend/.mvn/wrapper/maven-wrapper.properties": "Which Maven version the wrapper downloads",
    "backend/Dockerfile": "Recipe for packing the backend into a container image",
    "backend/mvnw": "Maven Wrapper for Mac/Linux: runs Maven without installing it",
    "backend/mvnw.cmd": "Maven Wrapper for Windows",
    "backend/pom.xml": "The backend's shopping list of libraries and build recipe",
    "backend/src/main/resources/application.yml": "All backend settings shared by every environment",
    "backend/src/main/resources/application-dev.yml": "Settings for running on a laptop (H2 database, demo data)",
    "backend/src/main/resources/application-docker.yml": "Settings for Docker (PostgreSQL, Redis)",
    "backend/src/main/resources/db/migration/V1__create_schema.sql": "Creates every database table, column and rule",
    J + "EduMateApplication.java": "The backend's ON switch (main method)",
    J + "config/AppProperties.java": "Typed copy of every edumate.* setting",
    J + "config/ClockConfig.java": "One shared clock in Indian Standard Time",
    J + "config/WebConfig.java": "Registers the CurrentUser parameter helper",
    J + "config/DemoDataSeeder.java": "Fills an empty database with realistic demo data",
    J + "common/ApiError.java": "The JSON shape of every error answer",
    J + "common/ApiException.java": "The error type our code throws on purpose",
    J + "common/GlobalExceptionHandler.java": "Turns every error into a friendly JSON answer",
    J + "common/audit/AuditEntry.java": "One row of the audit trail (who, what, before, after)",
    J + "common/audit/AuditRepository.java": "Reads and writes audit rows",
    J + "common/audit/AuditLogger.java": "The single place that writes audit records",
    J + "common/audit/AuditController.java": "GET /api/audit for administrators",
    J + "campus/Campus.java": "A campus (tenant) of the university",
    J + "campus/CampusRepository.java": "Reads and writes campuses",
    J + "campus/TenantProvisioner.java": "Creates campuses listed in application.yml at start-up",
    J + "security/Role.java": "The nine kinds of user",
    J + "security/AppUser.java": "A login account (with bcrypt password hash and lockout fields)",
    J + "security/AppUserRepository.java": "Reads and writes login accounts",
    J + "security/CurrentUser.java": "Who is making this request, read from the token",
    J + "security/CurrentUserArgumentResolver.java": "Lets controllers simply ask for a CurrentUser",
    J + "security/JwtTokenService.java": "Creates the signed login token (JWT)",
    J + "security/LoginAttemptService.java": "Checks passwords and locks accounts after 5 failures",
    J + "security/AuthController.java": "POST /api/auth/login and GET /api/auth/me",
    J + "security/RoleMatrix.java": "The complete list of who may call which URL (deny by default)",
    J + "security/RestAuthHandlers.java": "JSON answers for 401 and 403, with auditing",
    J + "security/SecurityConfig.java": "The security guard: tokens, roles, password hashing",
    J + "academic/Program.java": "A degree programme such as B.Tech CSE",
    J + "academic/ProgramRepository.java": "Reads programmes",
    J + "academic/Student.java": "One enrolled student",
    J + "academic/StudentRepository.java": "Finds students by section, USN, search text",
    J + "academic/Course.java": "A subject in one semester",
    J + "academic/CourseRepository.java": "Finds courses",
    J + "academic/ExamSession.java": "An examination session such as 2026-ODD",
    J + "academic/ExamSessionRepository.java": "Finds exam sessions",
    J + "academic/CourseAccess.java": "May THIS person touch THIS course?",
    J + "academic/AcademicController.java": "Lists of programmes, courses, rosters, sessions, student search",
    J + "attendance/AttendanceSession.java": "One class meeting whose attendance was taken (with @Version)",
    J + "attendance/AttendanceRecord.java": "Present/absent for one student in one session",
    J + "attendance/AttendanceSessionRepository.java": "Finds attendance sessions",
    J + "attendance/AttendanceRecordRepository.java": "Counts attendance with grouped queries",
    J + "attendance/AttendanceCount.java": "One row of a grouped attendance count",
    J + "attendance/AttendanceMath.java": "Exact attendance arithmetic (percent, can-miss, threshold)",
    J + "attendance/MedicalExemption.java": "An approved medical exemption",
    J + "attendance/MedicalExemptionRepository.java": "Finds medical exemptions",
    J + "attendance/EligibilityEvaluator.java": "The hall-ticket decision table (R1–R5)",
    J + "attendance/AttendanceSummaryService.java": "Percentages, can-miss and shortfall lists",
    J + "attendance/AttendanceCaptureService.java": "Take and correct attendance safely (fix for DR-01)",
    J + "attendance/ShortfallNotifier.java": "E-mails guardians of students below 75% (FR-31)",
    J + "attendance/AttendanceController.java": "Every /api/attendance URL",
    J + "exam/Mark.java": "Internal and external marks of a student in a course",
    J + "exam/MarkRow.java": "One row of the single cohort marks query",
    J + "exam/MarkRepository.java": "Marks queries, including the one-query cohort load (fix for DR-03)",
    J + "exam/GradeScale.java": "The R-2023 grade bands S…F and grade points",
    J + "exam/SgpaCalculator.java": "SGPA and CGPA formulas",
    J + "exam/ResultStatus.java": "Stages of a result set: DRAFT → … → PUBLISHED",
    J + "exam/ResultSet.java": "The results of one cohort in one exam session",
    J + "exam/ResultSetRepository.java": "Includes the atomic publish-if-approved update (fix for DEF-027)",
    J + "exam/StudentResult.java": "One student's SGPA, CGPA and pass/fail",
    J + "exam/CourseGrade.java": "One student's grade in one course",
    J + "exam/StudentResultRepository.java": "Results queries: history for CGPA, published results",
    J + "exam/PriorSemester.java": "An earlier semester's credits and SGPA",
    J + "exam/PublishedRow.java": "One published semester result row",
    J + "exam/CourseGradeRepository.java": "Finds course grades",
    J + "exam/ResultSetView.java": "What the Results page shows about a result set",
    J + "exam/ResultComputationService.java": "Computes SGPA/CGPA for a whole cohort",
    J + "exam/ResultPublicationService.java": "Two-person approval and one-time publishing",
    J + "exam/ResultQueryService.java": "A student's published results (cached)",
    J + "exam/MarksEntryService.java": "Marks amendment with old/new value audit (fix for DR-04)",
    J + "exam/HallTicketService.java": "Collects the inputs of the eligibility decision table",
    J + "exam/ExamController.java": "Every /api/exams URL",
    J + "exam/ReportService.java": "Consolidated marks and shortfall reports (and safe CSV)",
    J + "exam/ReportController.java": "Every /api/reports URL",
    J + "fees/FeeDemand.java": "A bill raised on a student",
    J + "fees/FeeDemandRepository.java": "Finds bills",
    J + "fees/Payment.java": "One attempt to pay through the gateway",
    J + "fees/PaymentRepository.java": "Payments queries, including the row-locking read",
    J + "fees/FeeLedgerEntry.java": "One line of a student's fee account book",
    J + "fees/FeeLedgerRepository.java": "Ledger lines and the balance query",
    J + "fees/FeeLedger.java": "Debit, credit and balance of a student's fees",
    J + "fees/GatewaySignature.java": "HMAC-SHA256 signing and checking of gateway callbacks",
    J + "fees/GatewayCallback.java": "The JSON the payment gateway sends",
    J + "fees/ReceiptNumberGenerator.java": "Unique receipt numbers",
    J + "fees/PaymentOrchestrator.java": "Starts payments; idempotent callback handling (fix for DR-02)",
    J + "fees/MockPaymentGateway.java": "A pretend bank for the demo",
    J + "fees/FeeAccountService.java": "Builds the fees page and accounts office views",
    J + "fees/FeeController.java": "Every /api/fees URL",
    J + "fees/PaymentGatewayController.java": "The gateway callback URL and the demo bank URLs",
    J + "admissions/AdmissionStatus.java": "States of an application",
    J + "admissions/AdmissionAction.java": "Buttons that move an application between states",
    J + "admissions/AdmissionStateMachine.java": "The table of allowed state changes (fix for DR-07)",
    J + "admissions/AdmissionApplication.java": "One person's application",
    J + "admissions/AdmissionApplicationRepository.java": "Finds and searches applications",
    J + "admissions/ApplicationForm.java": "The application form's JSON, with its rules",
    J + "admissions/AdmissionService.java": "Create, edit, submit and decide applications",
    J + "admissions/MeritListGenerator.java": "Ranks applicants and allocates seats (FR-05)",
    J + "admissions/AdmissionController.java": "Every /api/admissions URL except documents",
    J + "documents/FileKind.java": "PDF, JPEG or PNG",
    J + "documents/DocumentType.java": "Which documents exist and which file kinds each accepts",
    J + "documents/FileTypeSniffer.java": "Recognises files by their first bytes",
    J + "documents/ObjectStore.java": "The idea of a file cupboard (put, get, delete)",
    J + "documents/LocalFileObjectStore.java": "The file cupboard as a folder on disk",
    J + "documents/ApplicationDocument.java": "The database record of one uploaded file",
    J + "documents/ApplicationDocumentRepository.java": "Finds uploaded-file records",
    J + "documents/DocumentService.java": "The whole upload / download / delete pipeline",
    J + "documents/DocumentController.java": "Upload, list, download and delete URLs",
    J + "consent/ConsentRecord.java": "A guardian's consent (with hashed OTP)",
    J + "consent/ConsentRepository.java": "Finds consent records",
    J + "consent/ConsentRegistry.java": "Verifiable, revocable guardian consent (fix for RR-02)",
    J + "consent/ConsentController.java": "Every /api/consent URL",
    J + "timetable/TimetableEntry.java": "One lecture in the weekly timetable",
    J + "timetable/TimetableRepository.java": "Timetable queries",
    J + "timetable/TimetableSolver.java": "Backtracking timetable generator and clash detector",
    J + "timetable/TimetableService.java": "Generate, move, check, publish, workload",
    J + "timetable/TimetableController.java": "Every /api/timetable URL",
    J + "library/Book.java": "A title in the library (with @Version)",
    J + "library/BookRepository.java": "Searches the catalogue",
    J + "library/BookLoan.java": "One book lent to one student",
    J + "library/BookLoanRepository.java": "Finds loans",
    J + "library/FineCalculator.java": "Rs 2 per day late, at most Rs 200",
    J + "library/LibraryService.java": "Issue, return and list loans",
    J + "library/LibraryController.java": "Every /api/library URL",
    J + "notifications/NotificationMessage.java": "One e-mail or SMS in the outbox",
    J + "notifications/NotificationRepository.java": "Reads and writes the outbox",
    J + "notifications/NotificationService.java": "Queues a message (never twice)",
    J + "notifications/NotificationGateway.java": "Anything that can deliver a message",
    J + "notifications/LoggingNotificationGateway.java": "Development stand-in: writes messages to the log",
    J + "notifications/NotificationDispatcher.java": "Sends pending messages every 5 seconds (fix for DR-08)",
    J + "notifications/NotificationController.java": "GET /api/notifications/outbox",
    J + "dashboard/DashboardService.java": "The home-page tiles for each role",
    J + "dashboard/DashboardController.java": "GET /api/dashboard",
    J + "admin/AdminController.java": "GET /api/admin/role-matrix",
    T + "TestFixtures.java": "Helpers shared by the unit tests",
    T + "IntegrationTestBase.java": "Starts the whole app for integration tests",
    T + "PostgresCompatibilityTest.java": "Runs the main flows on a real PostgreSQL 17",
    T + "attendance/EligibilityEvaluatorTest.java": "Boundary values and the decision table (TC-008/009/010)",
    T + "attendance/AttendanceMathTest.java": "Percent, can-miss and max-achievable arithmetic",
    T + "attendance/AttendanceConcurrencyIntegrationTest.java": "Stale save refused with 409 (DR-01)",
    T + "exam/SgpaCalculatorTest.java": "TC-013 and the grade bands",
    T + "exam/ResultPublicationIntegrationTest.java": "Compute, two approvals, concurrent publish (TC-015)",
    T + "admissions/AdmissionStateMachineTest.java": "State transition testing (DR-07)",
    T + "admissions/AdmissionConsentIntegrationTest.java": "Guardian consent before submission (TC-020)",
    T + "timetable/TimetableSolverTest.java": "Clash-free generation and clash detection (TC-011)",
    T + "documents/UploadSafetyTest.java": "File sniffing, name cleaning, SHA-256",
    T + "fees/GatewaySignatureTest.java": "HMAC signatures detect tampering",
    T + "fees/PaymentIntegrationTest.java": "Replayed callback credits once (TC-005, TC-006)",
    T + "security/SecurityIntegrationTest.java": "403 on reports, 401, tampered token, lockout, no stack traces",
    T + "security/RoleMatrixCoverageTest.java": "Every endpoint must appear in the RoleMatrix",
    "frontend/Dockerfile": "Recipe for building the React app and serving it with nginx",
    "frontend/index.html": "The single HTML page React draws into",
    "frontend/nginx.conf": "nginx: serve the app, forward /api to the backend, add security headers",
    "frontend/package-lock.json": "Exact versions of every installed package (generated by npm)",
    "frontend/package.json": "The frontend's shopping list of packages and its commands",
    "frontend/public/favicon.svg": "The little logo in the browser tab",
    "frontend/tsconfig.json": "TypeScript compiler settings",
    "frontend/vite.config.ts": "Vite settings: port 5173 and the /api proxy to 8080",
    F + "main.tsx": "The first frontend code that runs",
    F + "App.tsx": "Which address shows which page, and who may open it",
    F + "config.ts": "Frontend settings that are not text or colours",
    F + "navigation.ts": "The left-hand menu for each role",
    F + "i18n/messages.ts": "EVERY piece of text shown on screen",
    F + "styles/theme.css": "EVERY colour, font and size",
    F + "styles/app.css": "How each kind of element looks",
    F + "api/types.ts": "The shape of every JSON object exchanged with the backend",
    F + "api/http.ts": "The one place that sends requests and handles errors",
    F + "api/endpoints.ts": "One function per backend URL",
    F + "auth/AuthContext.tsx": "Remembers who is logged in",
    F + "auth/RequireAuth.tsx": "Gate in front of pages (login and role)",
    F + "hooks/useLoad.ts": "The standard way a page loads data",
    F + "components/Toast.tsx": "Pop-up messages in the corner",
    F + "components/ConfirmDialog.tsx": "\"Are you sure?\" dialogs",
    F + "components/ui.tsx": "Small shared pieces: headers, alerts, badges, fields",
    F + "components/Layout.tsx": "Menu + top bar frame around every page",
    F + "components/ErrorBoundary.tsx": "Safety net: a crashing page shows a message instead of a blank screen",
    F + "components/TimetableGrid.tsx": "Draws a week as a grid",
    F + "components/DocumentUpload.tsx": "One document box: drag-and-drop, checks, progress, view, remove",
    F + "utils/format.ts": "Dates, money, percentages and file sizes as text",
    F + "utils/fileChecks.ts": "Checks files in the browser before uploading",
    F + "utils/validation.ts": "Application form checks and age calculation",
    F + "utils/fileChecks.test.ts": "Tests for the file checks",
    F + "utils/format.test.ts": "Tests for the formatting helpers",
    F + "utils/validation.test.ts": "Tests for form validation",
    F + "pages/LoginPage.tsx": "The sign-in screen",
    F + "pages/DashboardPage.tsx": "The home page tiles",
    F + "pages/NotFoundPage.tsx": "Page for unknown addresses",
    F + "pages/student/MyAttendancePage.tsx": "Student / guardian attendance",
    F + "pages/student/HallTicketPage.tsx": "Hall-ticket eligibility per course",
    F + "pages/student/MyResultsPage.tsx": "Published results",
    F + "pages/student/MyFeesPage.tsx": "Bills, payments, statement, Pay now",
    F + "pages/student/MockGatewayPage.tsx": "The pretend bank page",
    F + "pages/student/MyTimetablePage.tsx": "The published weekly timetable",
    F + "pages/student/MyLibraryPage.tsx": "Books borrowed and fines",
    F + "pages/faculty/TakeAttendancePage.tsx": "Take attendance (handles 409 stale saves)",
    F + "pages/faculty/CourseAttendancePage.tsx": "Class attendance, shortfall, e-mail guardians",
    F + "pages/faculty/MarksEntryPage.tsx": "Internal marks with a reason for every change",
    F + "pages/exam/ResultsManagePage.tsx": "Compute → approve → approve → publish",
    F + "pages/exam/ConsolidatedReportView.tsx": "Consolidated marks table and CSV download",
    F + "pages/exam/ReportsPage.tsx": "Shortfall and consolidated reports",
    F + "pages/admissions/ApplicationsPage.tsx": "Officer's list of applications",
    F + "pages/admissions/ApplicationDetailPage.tsx": "One application: details, documents, decisions",
    F + "pages/admissions/MeritListPage.tsx": "Merit list and seat allocation",
    F + "pages/applicant/ApplyPage.tsx": "Applicant: form, documents, consent, submit",
    F + "pages/accounts/PaymentsPage.tsx": "Accounts office: payments and ledgers",
    F + "pages/library/LibraryDeskPage.tsx": "Librarian: issue and return",
    F + "pages/admin/TimetableManagePage.tsx": "Generate, adjust, check and publish timetables",
    F + "pages/admin/AuditPage.tsx": "The audit trail",
    F + "pages/admin/OutboxPage.tsx": "Queued and sent e-mails / SMS",
    F + "pages/admin/RoleMatrixPage.tsx": "Who may call which URL",
}
