"""The A-Z glossary at the end of the guide. Plain-word definitions of every technical term used."""
import html

TERMS = {
    "API": "Application Programming Interface: the set of addresses (URLs) a program offers so other programs can talk to it. EduMate's backend API is every URL starting with /api/.",
    "Algorithm": "A precise, step-by-step recipe for solving a problem, e.g. \"sort by merit score, then fill open seats in rank order\".",
    "Annotation (Java)": "A label starting with @ written above a class, method or field (e.g. @Service, @Column). It changes nothing by itself; frameworks read it and act on it.",
    "ApplicationRunner": "A Spring component whose run() method is called once, right after the app has started. Used by TenantProvisioner and DemoDataSeeder.",
    "Argument / parameter": "A value handed to a function or method. In add(2, 3) the arguments are 2 and 3.",
    "Array / List": "An ordered collection of items: [\"A\", \"B\", \"C\"]. Position 0 is the first item.",
    "Arrow function": "JavaScript's short way to write a function: (x) => x * 2 means \"take x, give back x times 2\".",
    "Async / await": "JavaScript's way to wait for slow things (like a network request) without freezing the page. await pauses only this function until the answer arrives.",
    "Atomic": "All-or-nothing, as if it happened in a single instant. An atomic update cannot be interrupted half way by another user.",
    "Audit trail / audit log": "A permanent diary of important changes: who did what, to which record, when, and the value before and after.",
    "Authentication": "Proving who you are (username + password → token).",
    "Authorization": "Deciding what you are allowed to do (a STUDENT may not open the cohort report).",
    "Backend": "The part of the system running on the server: it stores data, applies the rules, and answers requests. EduMate's backend is Spring Boot on port 8080.",
    "Backtracking": "A search method: try a choice, continue, and if you get stuck, undo the last choice and try the next one. Used by the timetable solver.",
    "Base64 / Base64url": "A way to write any bytes using only letters, digits and a few symbols, so they can travel inside text such as a JWT.",
    "Bcrypt": "A password-hashing method that is deliberately slow (cost 12 ≈ 0.25 s), so guessing millions of passwords takes far too long.",
    "Bean (Spring)": "An object that Spring creates once and hands to every class that needs it.",
    "BigDecimal": "Java's exact decimal number. 0.1 + 0.2 is exactly 0.3 with BigDecimal (with double it is 0.30000000000000004).",
    "Blob": "A chunk of raw file data in the browser (e.g. a downloaded PDF), which can be shown or saved.",
    "Boolean": "A value that is either true or false.",
    "Boundary value analysis (BVA)": "A test design technique: test just below, exactly at, and just above a limit (74.99 %, 75.00 %, 75.01 %), because mistakes cluster at limits.",
    "Browser": "The program that shows web pages (Chrome, Edge, Firefox). The frontend runs inside it.",
    "Build": "Turning source code into something that runs: Java → .class files → a .jar; TypeScript/React → plain JavaScript files in dist/.",
    "Cache": "A fast memory of recent answers, so the same question need not be worked out again. EduMate caches published results (Redis in Docker).",
    "CAPTCHA": "(Not used.) A puzzle that tells humans from robots.",
    "Class": "A blueprint for objects in Java/TypeScript: it lists the fields (data) and methods (actions) every object of that kind has.",
    "Client": "The side that asks (the browser). The server is the side that answers.",
    "Column": "One kind of information in a database table (e.g. usn, full_name). Every row has a value for each column.",
    "Commit (database)": "Making a transaction's changes permanent.",
    "Commit (git)": "A saved snapshot of the project's files, with a message describing the change.",
    "Compile / compiler": "Translating human-written code into a form the computer runs, and checking it for mistakes on the way.",
    "Component (React)": "A function that returns what a part of the screen should look like, e.g. LoginPage or Badge.",
    "Concurrency": "Several things happening at the same time, e.g. two teachers saving the same register.",
    "Constructor": "The special method that builds a new object and fills its fields.",
    "Container / image (Docker)": "An image is a packed, ready-to-run copy of a program with everything it needs; a container is a running copy of an image.",
    "Content-Type": "An HTTP header saying what kind of data the body is: application/json, multipart/form-data, text/csv, application/pdf …",
    "Context (React)": "A value shared with every component below a Provider without passing it through each level (used for login state, toasts, confirm dialogs).",
    "CORS": "Browser rule that blocks a page on one address from reading answers from another address unless allowed. EduMate avoids it by serving everything from one address (proxy).",
    "CRLF / LF": "The invisible characters that end a line: Windows uses CR+LF, Linux/Mac use LF.",
    "CSRF": "Cross-Site Request Forgery: tricking a logged-in browser into sending a request. It needs login cookies; EduMate uses a header token, so it has nothing to ride on.",
    "CSS": "Cascading Style Sheets: the language for how things look (colours, sizes, spacing, layout).",
    "CSV": "Comma-Separated Values: a plain-text table that Excel can open.",
    "Cyclomatic complexity": "A count of the independent paths through a method (roughly: 1 + number of if/for/while/case). Higher = harder to test. The report's target is ≤ 10.",
    "Database": "An organised, permanent store of data, kept in tables. EduMate uses PostgreSQL (and H2 while developing).",
    "Decision table": "A table listing combinations of conditions and the action for each. Used for hall-ticket eligibility (rules R1–R5).",
    "Dependency": "A library that a project needs (listed in pom.xml or package.json).",
    "Dependency injection": "Instead of a class creating its helpers itself, Spring hands them in (usually through the constructor). Makes code easy to test and change.",
    "Deny by default": "Security principle: anything not explicitly allowed is forbidden. EduMate's RoleMatrix ends with anyRequest().denyAll().",
    "Deserialization": "Turning text (like JSON) back into objects in memory.",
    "DPDP Act / Rules": "India's Digital Personal Data Protection Act 2023 and Rules 2025; among other things they require verifiable parental consent before processing a child's data.",
    "DTO / record": "A small object whose only job is to carry data between layers or over the network. Java records (record X(...)) are perfect for this.",
    "Endpoint": "One URL + method the backend answers, e.g. GET /api/attendance/me.",
    "Entity": "A Java class whose objects are stored as rows in a database table (@Entity).",
    "Enum": "A type with a fixed list of allowed values, e.g. Role = ADMIN, FACULTY, STUDENT …",
    "Environment variable": "A named setting given to a program from outside (e.g. JWT_SECRET), so secrets are not written in the code.",
    "Equivalence partitioning": "Test design technique: split inputs into groups that behave the same, and test one value from each group.",
    "Error boundary": "A React component that catches crashes in the components inside it and shows a fallback instead of a blank page.",
    "Exception": "An error object that jumps out of the current method until something catches it.",
    "Fetch": "The browser's built-in function for sending HTTP requests from JavaScript.",
    "Field": "A named piece of data stored inside an object (e.g. a Student's usn).",
    "Filter chain (Spring Security)": "A line of checks every request passes through before reaching a controller: read token, verify signature, check role …",
    "Flyway": "A tool that runs numbered SQL files (V1__..., V2__...) exactly once each, so every database has the same, versioned structure.",
    "Foreign key": "A column that must match an id in another table, linking the two (student.program_id → program.id).",
    "FormData": "The browser's container for form fields and files, sent as multipart/form-data.",
    "Framework": "A large library that gives a program its structure and calls your code at the right moments (Spring Boot, React).",
    "Frontend": "The part of the system that runs in the browser and draws the screens: EduMate's React app.",
    "Function / method": "A named, reusable block of code that does one job. In Java, functions inside classes are called methods.",
    "Generic (type)": "A type with a slot for another type: List<String> is a list of texts, Promise<User> will deliver a User.",
    "Getter / setter": "Tiny methods to read (get) or change (set) a private field.",
    "Git / GitHub": "Git records every version of the project's files; GitHub stores that history online.",
    "H2": "A small database that can run inside the Java program's memory. Perfect for development: nothing to install, fresh data each start.",
    "Hash": "A fixed-size fingerprint of data (SHA-256). The same input always gives the same hash; you cannot get the input back from it.",
    "Header (HTTP)": "Extra name: value lines sent with a request or answer, e.g. Authorization: Bearer …, Content-Type: application/json.",
    "Hibernate / JPA": "JPA is the standard way to map Java objects to database tables; Hibernate is the library that does it (writes the SQL for you).",
    "HMAC": "A signature made from a message and a shared secret key. Anyone who changes the message cannot produce a matching signature without the key.",
    "Hook (React)": "A function starting with use… (useState, useEffect …) that gives a component memory or side effects.",
    "HTML": "HyperText Markup Language: describes the content and structure of a web page.",
    "HTTP": "The language browsers and servers use to talk: a request (method, URL, headers, body) and a response (status, headers, body).",
    "HTTP status code": "The 3-digit result of a request: 200 OK, 400 bad input, 401 not logged in, 403 not allowed, 404 not found, 409 conflict, 413 too large, 423 locked, 500 server error.",
    "Idempotent": "Doing it twice has the same effect as doing it once. The payment callback must be idempotent because gateways resend callbacks.",
    "Import": "A line that brings code from another file or library into this file.",
    "Index (database)": "An extra lookup structure that finds rows quickly without scanning the whole table.",
    "Integration test": "A test that runs several parts together (controller + service + database).",
    "Interface (Java)": "A promise of methods without their code; classes that implement it provide the code. ObjectStore is an interface.",
    "Interface (TypeScript)": "A description of the shape of an object (its field names and types).",
    "Jackson": "The library that turns Java objects into JSON and back.",
    "Jar": "A single Java archive file containing the compiled program and its libraries; run with java -jar.",
    "Java": "The programming language of the backend: strict types, compiled, runs on the Java Virtual Machine (JVM).",
    "JavaScript": "The programming language browsers run. TypeScript is turned into JavaScript.",
    "JPQL": "Java Persistence Query Language: SQL-like queries written with class and field names instead of table and column names.",
    "JSON": "JavaScript Object Notation: the text format for data, e.g. {\"username\": \"student\", \"age\": 20}. Every request and answer body in EduMate is JSON (except file uploads/downloads).",
    "JSX / TSX": "HTML-like tags written inside JavaScript/TypeScript to describe the screen: <button>Save</button>.",
    "JUnit": "The test framework for Java.",
    "JWT": "JSON Web Token: header.payload.signature. The payload says who you are; the signature proves the server issued it. EduMate's login \"wristband\".",
    "Latency": "How long it takes for an answer to come back.",
    "Library": "Ready-made code written by others that a project uses.",
    "Localhost": "\"This very computer\". http://localhost:8080 means port 8080 on your own machine.",
    "Lock (pessimistic)": "Reserve a database row so nobody else can change it until you finish (SELECT … FOR UPDATE).",
    "Lock (optimistic)": "Don't reserve anything; instead, when saving, check that nobody changed the row since you read it (a version number). Refuse the save if they did.",
    "Magic number (file)": "The first bytes of a file that identify its real type, e.g. %PDF- for PDFs.",
    "Maven": "The Java build tool: downloads libraries listed in pom.xml, compiles, tests and packages the backend.",
    "Merit list": "The ranked list of applicants by merit score, with seats allocated.",
    "Middleware / proxy": "A program in the middle that forwards requests. In EduMate, Vite (dev) and nginx (Docker) forward /api/… requests from the browser to the backend on port 8080.",
    "Migration": "A numbered script that changes the database structure (Flyway's V1__create_schema.sql).",
    "MockMvc": "A fake browser for tests: sends requests straight into the Spring app with no network.",
    "Multipart/form-data": "The request format for uploading files: the body is split into parts separated by a boundary line, one part per field or file.",
    "Multi-tenant": "One system serving several separate customers (here: campuses) whose data must not mix.",
    "N+1 query problem": "Loading a list with 1 query and then 1 more query per item (1 + N queries). Slow for big N. Fixed by loading everything in one query.",
    "nginx": "A fast web server. In Docker it serves the built frontend files and forwards /api to the backend.",
    "Node.js / npm": "Node.js runs JavaScript outside the browser (needed by the build tools); npm installs JavaScript packages listed in package.json.",
    "Null": "\"Nothing here\". A variable that holds no value.",
    "Object": "A bundle of data (fields) and behaviour (methods). In JavaScript also any { key: value } bundle.",
    "Object store": "A place that keeps files by name (key), like a labelled cupboard. EduMate stores uploaded scans in one.",
    "OTP": "One-Time Password: a short code (6 digits) valid once and for a few minutes.",
    "OWASP Top 10": "The ten most important web security risks (A01 broken access control, A02 cryptographic failures, A03 injection …).",
    "Outbox pattern": "Instead of sending e-mails in the middle of business logic, write them to an outbox table; a separate job sends them later.",
    "Package (Java)": "A folder of related classes, e.g. com.edumate.fees.",
    "Port": "A numbered door on a computer. One program listens on each: 5173 Vite, 8080 backend, 5432 PostgreSQL, 6379 Redis, 3000 nginx (Docker).",
    "PostgreSQL": "A powerful free database server; EduMate's production database.",
    "Primary key": "The column whose value uniquely identifies each row (usually id).",
    "Profile (Spring)": "A named set of settings. dev = H2 + demo data; docker = PostgreSQL + Redis.",
    "Promise": "JavaScript's \"I will give you the answer later\". await waits for it.",
    "Props (React)": "The inputs given to a component, like HTML attributes: <Badge tone=\"good\">.",
    "Proxy": "See Middleware / proxy.",
    "Query": "A question asked of the database (SELECT …) or a change (UPDATE …).",
    "React": "The JavaScript library that builds the screens from components and redraws them when data changes.",
    "Record (Java)": "A short way to write a class that just carries data: record Point(int x, int y).",
    "Redis": "A very fast in-memory data store, used as EduMate's cache in Docker.",
    "Regular expression (regex)": "A pattern for matching text, e.g. \\d{6} = exactly six digits.",
    "Repository": "In Spring Data, an interface for reading and writing one kind of entity; Spring writes the code from the method names.",
    "Request / response": "The browser's question to the server, and the server's answer.",
    "REST": "A style of API: resources at URLs, HTTP methods as verbs (GET reads, POST creates/does, PUT updates, DELETE removes), JSON bodies.",
    "Role": "A kind of user (STUDENT, FACULTY …). Permissions are given to roles, not to individual people.",
    "Rollback": "Undoing every change of a transaction because something failed.",
    "Row": "One record in a database table (one student, one payment).",
    "Salt": "Random data mixed into a password before hashing, so equal passwords give different hashes. Bcrypt does this automatically.",
    "Schema": "The structure of the database: its tables, columns and rules.",
    "Seed data": "Demo data put into an empty database at start-up.",
    "Serialization": "Turning objects in memory into text or bytes (e.g. JSON) to send or store.",
    "Server": "A program (and the computer running it) that waits for requests and answers them.",
    "Service": "A class holding business logic (@Service), between controllers and repositories.",
    "SessionStorage": "Browser storage that lasts until the tab is closed. EduMate keeps the login token there.",
    "SGPA / CGPA": "Semester / Cumulative Grade Point Average: Σ(credits × grade points) ÷ Σ credits, for one semester / all semesters so far.",
    "SHA-256": "A standard hash function producing a 64-hex-character fingerprint.",
    "Single-page application (SPA)": "A web app that loads one HTML page once and then redraws parts of it with JavaScript instead of loading new pages.",
    "Spring Boot": "A Java framework that sets up a web server, database access, security and more with very little code.",
    "SQL": "Structured Query Language: the language for creating tables and asking databases questions.",
    "SQL injection": "An attack where input is treated as SQL code. EduMate always uses parameters (:name), never string-glued SQL.",
    "State (React)": "A component's memory. Changing state makes React redraw the component.",
    "State machine": "A model of an object's possible states and the allowed moves between them (DRAFT → SUBMITTED → …).",
    "Stateless": "The server keeps no memory of a user between requests; each request carries its own token.",
    "Static typing": "Types (number, text …) are checked before the program runs, catching many mistakes early. Java and TypeScript do this.",
    "Stream (Java)": "A pipeline over a collection: list.stream().filter(...).map(...).toList().",
    "String": "Text, e.g. \"Hello\".",
    "Test case": "One specific check with given input and expected result (e.g. TC-009: 75.00 % → eligible).",
    "Thread": "One line of work inside a program. A server uses many threads to answer many users at once.",
    "Timeout": "A limit on how long to wait for something.",
    "Toast": "A small pop-up message that disappears after a few seconds.",
    "Token": "A string that proves who you are, sent with each request (EduMate: a JWT in the Authorization header).",
    "Transaction": "A group of database changes that succeed or fail together.",
    "TypeScript": "JavaScript with types. The frontend is written in TypeScript and translated to JavaScript for the browser.",
    "UNIQUE constraint": "A database rule that no two rows may share a value (or combination of values).",
    "Unit test": "A test of one small piece (one class or function) on its own.",
    "URL": "A web address: http://localhost:5173/fees?x=1 (protocol, host, port, path, query).",
    "UUID": "A random 128-bit id, practically never repeated.",
    "Validation": "Checking input against rules (required, max length, e-mail format, 0–100 …).",
    "Variable": "A named box that holds a value.",
    "Version control": "Keeping every past version of the files (git).",
    "Vite": "The frontend's development server (port 5173) and build tool.",
    "Vitest": "The test framework for the frontend.",
    "XSS": "Cross-Site Scripting: tricking a page into running someone else's script. React writes text as text, not HTML, which prevents it.",
    "XMLHttpRequest": "The older browser API for HTTP requests; used for uploads because it reports upload progress.",
    "YAML": "A settings-file format based on indentation (application.yml).",
    "Accessibility (a11y)": "Making software usable by everyone, including people who use a keyboard only, a screen reader, zoom, or who are sensitive to motion. \"a11y\" = a, 11 letters, y.",
    "AnimatePresence": "A motion component that keeps an element on screen after React removes it, until its exit animation has finished.",
    "ARIA": "Accessible Rich Internet Applications: HTML attributes (role, aria-label, aria-live, aria-pressed…) that tell screen readers what an element is and what state it is in.",
    "Backdrop filter": "A CSS effect that blurs or tints whatever is behind an element, giving a frosted-glass look (the top bar).",
    "Code splitting / lazy loading": "Cutting the app into several JavaScript files and downloading each page's file only when it is first opened (React.lazy + Suspense).",
    "Command palette": "A search box, opened with a keyboard shortcut (Ctrl K), that lists pages and actions and runs the chosen one.",
    "Compositor": "The part of the browser that assembles the finished layers of a page, often on the graphics card. Animating transform and opacity only needs the compositor, which is why they are smooth.",
    "Content-Security-Policy (CSP)": "A header that tells the browser which sources a page may load scripts, styles, fonts and workers from. EduMate allows only its own address, so injected scripts cannot run.",
    "Design system": "The shared rules and parts every screen uses: tokens (colours, sizes, curves) plus reusable components, so the product looks and behaves consistently.",
    "Design token": "A named design value, such as --color-primary or --space-4, used instead of a raw number. Change the token and every screen follows.",
    "Easing curve": "How an animation's speed changes over time. Ease-out starts fast and ends gently, which feels natural for things arriving.",
    "Focus ring": "The visible outline around the element that keyboard input goes to. It shows keyboard users where they are.",
    "Headless component": "A component that provides behaviour (keyboard, focus, ARIA) but no styling, so the app styles it itself. Radix UI is headless.",
    "Layout animation": "An animation between two positions or sizes of an element after the layout changed, e.g. the menu highlight sliding to the new page (motion's layoutId).",
    "Lenis": "A small library that makes wheel scrolling glide smoothly while keeping the browser's real scrolling underneath.",
    "Motion (library)": "The React animation library EduMate uses (formerly Framer Motion): initial / animate / exit, springs, layout animations and scroll-linked values.",
    "Motion value": "A value that motion updates many times a second and writes straight into an element's style, without making React redraw the page.",
    "OKLCH / OKLab": "Colour spaces built around human perception: equal lightness numbers look equally light. OKLCH writes a colour as lightness, chroma (colourfulness) and hue.",
    "Parallax": "Layers moving by different amounts (with the mouse or the scroll), which creates an impression of depth.",
    "Portal (React)": "Drawing a component somewhere else in the page's HTML (e.g. at the end of body) while it still belongs to its React parent. Used for dialogs, tooltips and the confetti canvas.",
    "Progressive enhancement": "Building a feature so that browsers that support it get the extra effect, while others still get a working page without it (e.g. the CSS scroll reveal inside @supports).",
    "Radix UI": "A library of headless, accessible building blocks for React: dialogs, drop-down menus, tooltips and more.",
    "Reduced motion": "An operating-system setting (prefers-reduced-motion) for people who feel unwell with animation. EduMate honours it everywhere.",
    "Screen reader": "Software that reads the screen aloud (NVDA, JAWS, VoiceOver) for people who cannot see it.",
    "Scroll-driven animation": "A CSS animation whose progress follows scrolling instead of time (animation-timeline: view() or scroll()).",
    "Shared layout animation": "See Layout animation: two elements with the same layoutId are treated as one thing moving between places.",
    "Skeleton screen": "Grey placeholder shapes of the content that is loading. Feels faster than a spinner, and the page does not jump when the content arrives.",
    "Spring animation": "An animation that behaves like a physical spring (stiffness, damping, mass): it can overshoot a little and settle, which feels lively.",
    "Stagger": "Starting the same animation on several elements one after another, a few hundredths of a second apart.",
    "Sticky positioning": "CSS position: sticky: an element scrolls normally until it reaches a set distance from the top of the window, then stays pinned there while its section scrolls on.",
    "SVG": "Scalable Vector Graphics: pictures described as shapes and lines in text form, sharp at any size. The rings, chart and logo are SVG.",
    "Tree shaking": "Removing code that is imported but never used when the app is built, so only the icons and functions actually used are shipped.",
    "View Transitions API": "A browser feature that takes a picture of the page before a change and animates to the new state; EduMate uses it for the circular theme switch.",
    "WCAG": "Web Content Accessibility Guidelines: the international standard for accessible web pages.",
    "Web font": "A font file downloaded with the page instead of relying on the computer's own fonts. EduMate bundles its fonts with the app.",
}


def glossary_html() -> str:
    items = sorted(TERMS.items(), key=lambda kv: kv[0].lower())
    rows = "".join(f"<tr><td><strong>{html.escape(k)}</strong></td><td>{html.escape(v)}</td></tr>" for k, v in items)
    return f'<table class="catalogue"><thead><tr><th>Term</th><th>Meaning in plain words</th></tr></thead><tbody>{rows}</tbody></table>'
