-- =====================================================================
-- EduMate database schema, version 1.
-- Flyway runs this file exactly once on an empty database and records
-- that it did so in its own table (flyway_schema_history).
-- The SQL is written so that it runs unchanged on PostgreSQL 15+ and on
-- H2 (the in-memory database used during development).
-- =====================================================================

-- ---------- Tenancy: one row per campus (multi-tenant platform) ----------
CREATE TABLE campus (
    code        VARCHAR(20)  PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    city        VARCHAR(80)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ---------- Academic structure ----------
CREATE TABLE program (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)  NOT NULL,
    name         VARCHAR(120) NOT NULL,
    level        VARCHAR(10)  NOT NULL,            -- UG, PG or PHD
    total_seats  INT          NOT NULL,
    campus_code  VARCHAR(20)  NOT NULL REFERENCES campus (code),
    CONSTRAINT uq_program_code UNIQUE (campus_code, code)
);

CREATE TABLE student (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usn             VARCHAR(20)  NOT NULL UNIQUE,  -- University Seat Number
    full_name       VARCHAR(120) NOT NULL,
    date_of_birth   DATE         NOT NULL,
    email           VARCHAR(160),
    phone           VARCHAR(20),
    program_id      BIGINT       NOT NULL REFERENCES program (id),
    semester        INT          NOT NULL,
    section         VARCHAR(10)  NOT NULL,
    guardian_name   VARCHAR(120),
    guardian_email  VARCHAR(160),
    guardian_phone  VARCHAR(20),
    campus_code     VARCHAR(20)  NOT NULL REFERENCES campus (code)
);

-- ---------- People who can log in ----------
CREATE TABLE app_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(60)  NOT NULL UNIQUE,
    password_hash    VARCHAR(100) NOT NULL,        -- bcrypt, cost 12 (OWASP A02)
    full_name        VARCHAR(120) NOT NULL,
    email            VARCHAR(160),
    role             VARCHAR(30)  NOT NULL,
    campus_code      VARCHAR(20)  NOT NULL REFERENCES campus (code),
    student_id       BIGINT REFERENCES student (id), -- STUDENT: self, GUARDIAN: their child
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_attempts  INT          NOT NULL DEFAULT 0, -- lockout counter (OWASP A07)
    locked_until     TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE course (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(20)  NOT NULL,
    name          VARCHAR(120) NOT NULL,
    credits       INT          NOT NULL,
    weekly_hours  INT          NOT NULL,
    program_id    BIGINT       NOT NULL REFERENCES program (id),
    semester      INT          NOT NULL,
    faculty_id    BIGINT REFERENCES app_user (id),
    CONSTRAINT uq_course_code UNIQUE (program_id, code)
);

CREATE TABLE exam_session (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20) NOT NULL UNIQUE,      -- e.g. 2026-ODD
    name         VARCHAR(80) NOT NULL,
    starts_on    DATE        NOT NULL,
    campus_code  VARCHAR(20) NOT NULL REFERENCES campus (code)
);

-- ---------- Attendance (FR-11, FR-12) ----------
CREATE TABLE attendance_session (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT      NOT NULL REFERENCES course (id),
    section       VARCHAR(10) NOT NULL,
    session_date  DATE        NOT NULL,
    period        INT         NOT NULL,
    taken_by      BIGINT      NOT NULL REFERENCES app_user (id),
    version       BIGINT      NOT NULL DEFAULT 0,  -- optimistic lock (fix for DR-01)
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_attendance_session UNIQUE (course_id, section, session_date, period)
);

CREATE TABLE attendance_record (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT  NOT NULL REFERENCES attendance_session (id) ON DELETE CASCADE,
    student_id  BIGINT  NOT NULL REFERENCES student (id),
    present     BOOLEAN NOT NULL,
    CONSTRAINT uq_attendance_record UNIQUE (session_id, student_id)
);

CREATE TABLE medical_exemption (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT       NOT NULL REFERENCES student (id),
    course_id    BIGINT       NOT NULL REFERENCES course (id),
    reason       VARCHAR(300) NOT NULL,
    approved     BOOLEAN      NOT NULL DEFAULT FALSE,
    approved_by  VARCHAR(60),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_medical_exemption UNIQUE (student_id, course_id)
);

-- ---------- Examinations and results (FR-17, FR-19) ----------
CREATE TABLE mark (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id               BIGINT       NOT NULL REFERENCES student (id),
    course_id                BIGINT       NOT NULL REFERENCES course (id),
    exam_session_id          BIGINT       NOT NULL REFERENCES exam_session (id),
    internal_marks           NUMERIC(5,2),         -- out of 40
    external_marks           NUMERIC(5,2),         -- out of 60
    revalued_external_marks  NUMERIC(5,2),         -- supersedes external_marks (RR-08)
    version                  BIGINT       NOT NULL DEFAULT 0,
    updated_by               VARCHAR(60),
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    -- One mark row per student, subject and exam session (fix for DR-05).
    CONSTRAINT uq_mark_student_course_session UNIQUE (student_id, course_id, exam_session_id)
);

CREATE TABLE result_set (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_id      BIGINT      NOT NULL REFERENCES exam_session (id),
    program_id           BIGINT      NOT NULL REFERENCES program (id),
    semester             INT         NOT NULL,
    status               VARCHAR(30) NOT NULL,     -- DRAFT, COMPUTED, AWAITING_SECOND_APPROVAL, APPROVED, PUBLISHED
    computed_at          TIMESTAMP WITH TIME ZONE,
    computed_by          VARCHAR(60),
    first_approver       VARCHAR(60),
    first_approved_at    TIMESTAMP WITH TIME ZONE,
    second_approver      VARCHAR(60),
    second_approved_at   TIMESTAMP WITH TIME ZONE,
    published_by         VARCHAR(60),
    published_at         TIMESTAMP WITH TIME ZONE,
    version              BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_result_set UNIQUE (exam_session_id, program_id, semester)
);

CREATE TABLE student_result (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_set_id       BIGINT       NOT NULL REFERENCES result_set (id) ON DELETE CASCADE,
    student_id          BIGINT       NOT NULL REFERENCES student (id),
    sgpa                NUMERIC(4,2) NOT NULL,
    cgpa                NUMERIC(4,2) NOT NULL,
    credits_registered  INT          NOT NULL,
    credits_earned      INT          NOT NULL,
    outcome             VARCHAR(10)  NOT NULL,     -- PASS or FAIL
    CONSTRAINT uq_student_result UNIQUE (result_set_id, student_id)
);

CREATE TABLE course_grade (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_result_id  BIGINT       NOT NULL REFERENCES student_result (id) ON DELETE CASCADE,
    course_id          BIGINT       NOT NULL REFERENCES course (id),
    total_marks        NUMERIC(5,2) NOT NULL,
    grade              VARCHAR(2)   NOT NULL,
    grade_point        INT          NOT NULL,
    credits            INT          NOT NULL
);

-- ---------- Fees and payments (FR-08) ----------
CREATE TABLE fee_demand (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT        NOT NULL REFERENCES student (id),
    description  VARCHAR(160)  NOT NULL,
    amount       NUMERIC(12,2) NOT NULL,
    due_date     DATE          NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE payment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id        BIGINT        NOT NULL REFERENCES student (id),
    fee_demand_id     BIGINT        NOT NULL REFERENCES fee_demand (id),
    amount            NUMERIC(12,2) NOT NULL,
    status            VARCHAR(20)   NOT NULL,      -- INITIATED, SUCCESS, FAILED
    gateway_order_id  VARCHAR(64)   NOT NULL UNIQUE,
    gateway_txn_ref   VARCHAR(64)   UNIQUE,        -- unique: a replayed callback cannot credit twice (fix for DR-02 / DEF-014)
    receipt_no        VARCHAR(40)   UNIQUE,
    failure_reason    VARCHAR(200),
    version           BIGINT        NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE fee_ledger_entry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT        NOT NULL REFERENCES student (id),
    entry_type   VARCHAR(10)   NOT NULL,           -- DEBIT (money owed) or CREDIT (money paid)
    amount       NUMERIC(12,2) NOT NULL,
    description  VARCHAR(200)  NOT NULL,
    reference    VARCHAR(64)   NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ledger_reference UNIQUE (entry_type, reference)
);

-- ---------- Admissions, documents and consent (FR-05, NFR-07) ----------
CREATE TABLE admission_application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no      VARCHAR(30)  NOT NULL UNIQUE,
    applicant_user_id   BIGINT       REFERENCES app_user (id),
    full_name           VARCHAR(120) NOT NULL,
    date_of_birth       DATE         NOT NULL,
    email               VARCHAR(160) NOT NULL,
    phone               VARCHAR(20),
    program_id          BIGINT       NOT NULL REFERENCES program (id),
    category            VARCHAR(10)  NOT NULL,     -- GEN, OBC, SC, ST
    entrance_score      NUMERIC(6,2),
    qualifying_percent  NUMERIC(5,2),
    guardian_name       VARCHAR(120),
    guardian_email      VARCHAR(160),
    guardian_phone      VARCHAR(20),
    status              VARCHAR(30)  NOT NULL,
    status_reason       VARCHAR(300),
    submitted_at        TIMESTAMP WITH TIME ZONE,
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE application_document (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id     BIGINT        NOT NULL REFERENCES admission_application (id),
    doc_type           VARCHAR(30)   NOT NULL,     -- MARKSHEET_10, MARKSHEET_12, ID_PROOF, PHOTO, ...
    original_filename  VARCHAR(200)  NOT NULL,
    storage_key        VARCHAR(300)  NOT NULL UNIQUE,
    content_type       VARCHAR(100)  NOT NULL,     -- detected from the bytes, not trusted from the browser
    size_bytes         BIGINT        NOT NULL,
    sha256             VARCHAR(64)   NOT NULL,
    uploaded_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE consent_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id    BIGINT       NOT NULL REFERENCES admission_application (id),
    purpose           VARCHAR(80)  NOT NULL,
    guardian_name     VARCHAR(120) NOT NULL,
    guardian_contact  VARCHAR(160) NOT NULL,
    status            VARCHAR(20)  NOT NULL,       -- PENDING, GRANTED, REVOKED
    otp_hash          VARCHAR(100),
    otp_expires_at    TIMESTAMP WITH TIME ZONE,
    otp_attempts      INT          NOT NULL DEFAULT 0,
    granted_at        TIMESTAMP WITH TIME ZONE,
    revoked_at        TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ---------- Audit trail (fix for DR-04: old AND new value) ----------
CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor        VARCHAR(60)   NOT NULL,
    action       VARCHAR(60)   NOT NULL,
    entity_type  VARCHAR(60)   NOT NULL,
    entity_id    VARCHAR(60)   NOT NULL,
    old_value    VARCHAR(4000),
    new_value    VARCHAR(4000),
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_entity ON audit_log (entity_type, entity_id);

-- ---------- Outgoing e-mail / SMS queue (FR-31, fix for DR-08) ----------
CREATE TABLE notification_outbox (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel     VARCHAR(10)   NOT NULL,            -- EMAIL or SMS
    recipient   VARCHAR(160)  NOT NULL,
    subject     VARCHAR(200)  NOT NULL,
    body        VARCHAR(4000) NOT NULL,
    status      VARCHAR(10)   NOT NULL,            -- PENDING, SENT, FAILED
    attempts    INT           NOT NULL DEFAULT 0,
    dedup_key   VARCHAR(200)  NOT NULL UNIQUE,     -- the same message is never queued twice
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at     TIMESTAMP WITH TIME ZONE
);

-- ---------- Timetable (FR-14) ----------
CREATE TABLE timetable_entry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id   BIGINT      NOT NULL REFERENCES program (id),
    semester     INT         NOT NULL,
    section      VARCHAR(10) NOT NULL,
    day_of_week  INT         NOT NULL,             -- 1 = Monday ... 6 = Saturday
    period       INT         NOT NULL,             -- 1 ... 6
    course_id    BIGINT      NOT NULL REFERENCES course (id),
    faculty_id   BIGINT      NOT NULL REFERENCES app_user (id),
    room         VARCHAR(20) NOT NULL,
    status       VARCHAR(12) NOT NULL              -- DRAFT or PUBLISHED
);

-- ---------- Library ----------
CREATE TABLE book (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn              VARCHAR(20)  NOT NULL UNIQUE,
    title             VARCHAR(200) NOT NULL,
    author            VARCHAR(160) NOT NULL,
    copies_total      INT          NOT NULL,
    copies_available  INT          NOT NULL,
    campus_code       VARCHAR(20)  NOT NULL REFERENCES campus (code),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_book_copies CHECK (copies_available >= 0 AND copies_available <= copies_total)
);

CREATE TABLE book_loan (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id      BIGINT       NOT NULL REFERENCES book (id),
    student_id   BIGINT       NOT NULL REFERENCES student (id),
    issued_on    DATE         NOT NULL,
    due_on       DATE         NOT NULL,
    returned_on  DATE,
    fine_amount  NUMERIC(8,2) NOT NULL DEFAULT 0
);
